if ((typeof(tPHk9GaLcTWd6cjlTMl2vl$3ast$3lex$0index$1)) == "undefined") {tPHk9GaLcTWd6cjlTMl2vl$3ast$3lex$0index$1 = {};
};
(function(){tPHk9GaLcTWd6cjlTMl2vl$3ast$3lex$0index$1.it$52;
var repl_element$53;
var v$58 = (function(d,id){return SmlPrims.option(d.getElementById(id));})(z11cymP27JOrM6FBeJkkje$3js$0Js$1.document$86,"lexer");
switch (v$58[0]) { case 0: {repl_element$53 = v$58[1];
 break; }default: {var repl_element$61 = document.createElement("div");
(function(e,a,b){return e.setAttribute(a,b);})(repl_element$61,"id","lexer");
(function(e,a){return e.appendChild(a);})((function(d){return d.documentElement;})(z11cymP27JOrM6FBeJkkje$3js$0Js$1.document$86),repl_element$61);
repl_element$53 = repl_element$61;
} };
var code_output$66 = document.createElement("div");
var code_input$67 = document.createElement("textarea");
var code_button$68 = document.createElement("button");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$53,"style"),"width","80%");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$53,"style"),"margin","20px auto");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$53,"style"),"border","1px solid #ccc");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$53,"style"),"padding","15px");
(function(e,a,b){return e.setAttribute(a,b);})(code_input$67,"rows","3");
(function(e,a,b){return e.setAttribute(a,b);})(code_input$67,"placeholder","(1,2,3,4)");
(function(e,a,b){return e.setAttribute(a,b);})(code_input$67,"spellcheck","false");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_input$67,"style"),"width","100%");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_input$67,"style"),"resize","vertical");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_input$67,"style"),"font-family","monospace");
(function(e,s){e.innerHTML = s;})(code_input$67,"(1,2,3,4)");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$66,"style"),"min-height","150px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$66,"style"),"white-space","pre");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$66,"style"),"background-color","#f0f0f0");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$66,"style"),"padding","10px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$66,"style"),"margin-bottom","10px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$66,"style"),"overflow-y","auto");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$66,"style"),"border","1px solid #eee");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$66,"style"),"font-family","monospace");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$68,"style"),"padding","8px 15px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$68,"style"),"background-color","#007bff");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$68,"style"),"color","white");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$68,"style"),"border","none");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$68,"style"),"cursor","pointer");
(function(e,s){e.innerHTML = s;})(code_button$68,"analyze");
(function(e,a){return e.appendChild(a);})(repl_element$53,code_output$66);
(function(e,a){return e.appendChild(a);})(repl_element$53,code_input$67);
(function(e,a){return e.appendChild(a);})(repl_element$53,code_button$68);
var v$313 = 4;
tPHk9GaLcTWd6cjlTMl2vl$3ast$3lex$0index$1.it$52 = (z11cymP27JOrM6FBeJkkje$3js$0Js$1.installEventHandler$195(code_button$68,v$313,function(v$315){var t$320 = code_output$66;
var t$318;
try {t$318 = (DiosqAwT1DBhTLq1ucomAd$3ast$3lex$0ast$3lex$1$4.analyze$3412((function(e){return e.value;})(code_input$67)));
} catch(v$317) {t$318 = ((function(v$316){var t$319 = v$316;
if (t$319[0] == sWBNi829bz3yxJwtxAWd8b$3basis$0Initial$1.en$Fail$52) {return v$316[1];
} else {throw v$316;
};
})(v$317));
};
(function(e,s){e.innerHTML = s;})(t$320,t$318);
return false;
}));
return 0;
})();
