if ((typeof(xBkhJL9x9X6b24WvjWPahm$3ast$3parse$0index$1)) == "undefined") {xBkhJL9x9X6b24WvjWPahm$3ast$3parse$0index$1 = {};
};
(function(){xBkhJL9x9X6b24WvjWPahm$3ast$3parse$0index$1.it$52;
var repl_element$54;
var v$59 = (function(d,id){return SmlPrims.option(d.getElementById(id));})(z11cymP27JOrM6FBeJkkje$3js$0Js$1.document$86,"parser");
switch (v$59[0]) { case 0: {repl_element$54 = v$59[1];
 break; }default: {var repl_element$62 = document.createElement("div");
(function(e,a,b){return e.setAttribute(a,b);})(repl_element$62,"id","parser");
(function(e,a){return e.appendChild(a);})((function(d){return d.documentElement;})(z11cymP27JOrM6FBeJkkje$3js$0Js$1.document$86),repl_element$62);
repl_element$54 = repl_element$62;
} };
var code_output$67 = document.createElement("div");
var code_input$68 = document.createElement("textarea");
var code_button$69 = document.createElement("button");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$54,"style"),"width","80%");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$54,"style"),"margin","20px auto");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$54,"style"),"border","1px solid #ccc");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$54,"style"),"padding","15px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(repl_element$54,"style"),"font-family","monospace");
(function(e,a,b){return e.setAttribute(a,b);})(code_input$68,"rows","4");
(function(e,a,b){return e.setAttribute(a,b);})(code_input$68,"placeholder","fix f = fn x => (g 10) + 1\n  | g = fn x => x+1\n in f 10\nend");
(function(e,a,b){return e.setAttribute(a,b);})(code_input$68,"spellcheck","false");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_input$68,"style"),"width","100%");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_input$68,"style"),"resize","vertical");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_input$68,"style"),"font-family","monospace");
(function(e,s){e.innerHTML = s;})(code_input$68,"fix f = fn x => (g 10) + 1\n  | g = fn x => x+1\n in f 10\nend");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$67,"style"),"min-height","150px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$67,"style"),"white-space","pre");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$67,"style"),"background-color","#f0f0f0");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$67,"style"),"padding","10px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$67,"style"),"margin-bottom","10px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$67,"style"),"overflow-y","auto");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_output$67,"style"),"border","1px solid #eee");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$69,"style"),"padding","8px 15px");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$69,"style"),"background-color","#007bff");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$69,"style"),"color","white");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$69,"style"),"border","none");
(function(fp,s,v){fp[s] = v;})((function(fp,s){return fp[s];})(code_button$69,"style"),"cursor","pointer");
(function(e,s){e.innerHTML = s;})(code_button$69,"parse");
(function(e,a){return e.appendChild(a);})(repl_element$54,code_output$67);
(function(e,a){return e.appendChild(a);})(repl_element$54,code_input$68);
(function(e,a){return e.appendChild(a);})(repl_element$54,code_button$69);
var v$314 = 4;
xBkhJL9x9X6b24WvjWPahm$3ast$3parse$0index$1.it$52 = (z11cymP27JOrM6FBeJkkje$3js$0Js$1.installEventHandler$195(code_button$69,v$314,function(v$316){var t$321 = code_output$67;
var t$319;
try {t$319 = (H0guHwGwLsFcjs20H3kvec$3ast$3parse$0ast$3parse$1$10.parse$10518((function(e){return e.value;})(code_input$68)));
} catch(v$318) {t$319 = ((function(v$317){var t$320 = v$317;
if (t$320[0] == sWBNi829bz3yxJwtxAWd8b$3basis$0Initial$1.en$Fail$52) {return v$317[1];
} else {throw v$317;
};
})(v$318));
};
(function(e,s){e.innerHTML = s;})(t$321,t$319);
return false;
}));
return 0;
})();
